# ifndef CONFIG_H
# define CONFIG_H
# define APPNAME "Q Light Controller Plus"
# define FXEDNAME "Fixture Definition Editor"
# define APPVERSION "MM Custom-201805"
# define DOCSDIR "/usr/share/qlcplus/documents"
# define INPUTPROFILEDIR "/usr/share/qlcplus/inputprofiles"
# define USERQLCPLUSDIR ".qlcplus"
# define USERINPUTPROFILEDIR ".qlcplus/inputprofiles"
# define MIDITEMPLATEDIR "/usr/share/qlcplus/miditemplates"
# define USERMIDITEMPLATEDIR ".qlcplus/miditemplates"
# define MODIFIERSTEMPLATEDIR "/usr/share/qlcplus/modifierstemplates"
# define USERMODIFIERSTEMPLATEDIR ".qlcplus/modifierstemplates"
# define FIXTUREDIR "/usr/share/qlcplus/fixtures"
# define USERFIXTUREDIR ".qlcplus/fixtures"
# define PLUGINDIR "/usr/lib/x86_64-linux-gnu/qt5/plugins/qlcplus"
# define AUDIOPLUGINDIR "/usr/lib/x86_64-linux-gnu/qt5/plugins/qlcplus/audio"
# define TRANSLATIONDIR "/usr/share/qlcplus/translations"
# define RGBSCRIPTDIR "/usr/share/qlcplus/rgbscripts"
# define USERRGBSCRIPTDIR ".qlcplus/rgbscripts"
# define GOBODIR "/usr/share/qlcplus/gobos"
# define WEBFILESDIR "/usr/share/qlcplus/web"
# endif
